apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin
        ports:
        - containerPort: 9000
        env:
          - name: PMA_ARBITRARY
            value: "mysql-service"
          - name: PMA_HOST
            value: "mysql-service"
          - name: PMA_PORT
            value: "3306"
