apiVersion: v1
kind: Secret
metadata:
  name: phpmyadmin-secret
type: Opaque
data:
  PMA_ARBITRARY: bXlzcWwtc2VydmljZQ== #mysql-service
  PMA_HOST: bXlzcWwtc2VydmljZQ== #mysql-service
  PMA_PORT: MzMwNg== #3306
