apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
    #ADICIONAR CONFIGMAP E SECRET
    #ADICIONAR RESOURCE LIMIT E REQUEST
    #ADICIONAR VOLUME
      containers:
        - name: wordpress
          image: wordpress:6.0.0
          ports:
            - containerPort: 80
          env:
          - name: WORDPRESS_DB_HOST
            value: "mysql-service"
          - name: WORDPRESS_DB_USER
            value: "usermysql"
          - name: WORDPRESS_DB_PASSWORD
            value: "pwdmysql"
          - name: WORDPRESS_DB_NAME
            value: "db_wordpress"
