apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      volumes:
      - name: vol-wordpress
        persistentVolumeClaim:
          claimName: vol-wordpress
      containers:
      - name: wordpress
        image: wordpress:6.1.1-php8.1-apache
        ports:
          - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: "mysql-service"
        envFrom:
        - secretRef:
            name: secret-wordpress
        volumeMounts:
        - mountPath: "/var/www/html"
          name: vol-wordpress