apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
    #ADICIONAR RESOURCE LIMIT E REQUEST
    #ADICIONAR VOLUME
      containers:
        - name: wordpress
          image: wordpress:6.0.0
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: secret-wordpress
