apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  selector:
    app: wordpress
  ports:
    - port: 80
      targetPort: 80
  #type: NodePort #para uso com cluster on-premise
  #type: LoadBalancer #para uso com cluster cloud
  type: ClusterIP #Para uso com Ingress