apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: pwdrootmysql
          - name: MYSQL_DATABASE
            value: db_wordpress
          - name: MYSQL_USER
            value: usermysql
          - name: MYSQL_PASSWORD
            value: pwdmysql