apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-mysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi