apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cHdkcm9vdG15c3Fs #pwdrootmysql
  MYSQL_DATABASE: ZGJfd29yZHByZXNz #db_wordpress
  MYSQL_USER: dXNlcm15c3Fs #usermysql
  MYSQL_PASSWORD: cHdkbXlzcWw= #pwdmysql
